stages:
  - lint
  - test

default:
  image: rust:latest
  cache: 
    key: cache-key
    untracked: true
    paths:
    - target/

clippy:
  stage: lint
  before_script:
    - rustup component add clippy
  script: 
    - cargo clippy -- -D warnings

check:
  stage: lint
  script:
    - cargo check

test:
  stage: test
  script:
    - cargo test
